# https://taskfile.dev

version: '3'

vars:
  JAR_FILE: target/finance-reports-1.0-SNAPSHOT-jar-with-dependencies.jar
  LEDGER_DIR: "{{.HOME}}/myledger"

tasks:
  default:
    cmds:
      - task -a
    silent: true
    desc: Lists the available tasks

  clean:
    desc: Clean everything
    cmds:
      - mvn clean

  test:
    desc: Run the tests
    cmds:
      - mvn test

  gen-jar:
    desc: Builds the executable JAR
    cmds:
      - mvn compile assembly:single
    sources:
      - pom.xml
      - src/main/java/**/*.java
      - src/main/kotlin/**/*.kt
    generates:
      - "{{.JAR_FILE}}"

  run:
    deps: [gen-jar]
    desc: Run with `task run`
    cmds:
      - java --enable-native-access=ALL-UNNAMED --class-path {{.JAR_FILE}} finrpts.app.AppRunner {{.LEDGER_DIR}}

  upgrade-list:
    desc: Report on available upgrades
    cmds:
      - mvn versions:display-plugin-updates
      - mvn versions:display-dependency-updates
